# Generated by Django 5.2.4 on 2025-08-04 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestion",
            name="no_votes",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="yes_votes",
        ),
        migrations.AddField(
            model_name="suggestion",
            name="no_voters",
            field=models.ManyToManyField(
                blank=True, related_name="suggestions_no", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="yes_voters",
            field=models.ManyToManyField(
                blank=True, related_name="suggestions_yes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
