# Generated by Django 5.2.4 on 2025-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(
                blank=True, default="https://via.placeholder.com/150"
            ),
        ),
    ]
