# Generated by Django 5.2.4 on 2025-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(
                default="https://example.com/static/icons/default_avatar.svg"
            ),
        ),
    ]
