# Generated by Django 5.2.4 on 2025-08-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.CharField(
                blank=True, default="/static/icons/default_avatar.svg", max_length=255
            ),
        ),
    ]
