# Generated by Django 5.2.4 on 2025-08-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
