# Generated by Django 5.2.4 on 2025-07-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspections", "0001_initial"),
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="suggestions.machine"
            ),
        ),
    ]
